application: api-assignment3b
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "60s"

handlers:
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest